alert("Hi hi pretty!") 
alert("i miss you!!")
alert("Anyways, i want to tell you something...")
alert("uhmm..")
alert("you're so pretty!")
alert("i like you a lot po hehe")
alert("i'll keep on waiting for you my princess")
alert("I promise, pinky promise!")
alert("so, just focus po sa pag study mo, goodluck!!")
alert("let's wait for the right time. :)")
